name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy on every push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment with the latest LTS version
      - name: Set up Latest Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'  # Always use the latest LTS version of Node.js

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Angular application
      - name: Build Angular app
        run: npm run build -- --output-path=dist/ygofm-fusion/browser --base-href /ygofm-fusion/

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/ygofm-fusion  # Output directory for the built Angular app
          publish_branch: gh-pages  # Optional: Defaults to gh-pages
