name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # If you need to build (e.g., a static site generator), add build steps here
      #- name: Build site
      #  run: npm install && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/ygofm-fusion       # or ./docs or ./build, depending on your setup
          publish_branch: gh-pages  # optional: defaults to gh-pages
